options:
  logging: CLOUD_LOGGING_ONLY
  pool: {}
projectId: seolab-408619
steps:
- name: gcr.io/k8s-skaffold/pack
  entrypoint: gunicorn -b :$PORT main:app
  args:
  - build
  - cloud-run-source-deploy
  - --builder
  - gcr.io/buildpacks/builder:latest